api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    metadata_backward_compatibility_layer: false
    defaults:
        attributes:
            normalization_context: { groups: ['concert:read'] }
            denormalization_context: { groups: ['concert:write'] }
